version: '3.4'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: "/usr/src/app"
    restart: on-failure:5
    #env_file:
      #- .env
    environment:
      - LANG=C.UTF-8
      - FLASK_APP=run.py
      - APP_ENVIRONMENT=development
